version: "2"
services:
  etcd:
    image: quay.io/coreos/etcd
    command: etcd --initial-cluster-state new --listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://127.0.0.1:2379
    volumes:
      - ./etcd-data:/default.etcd
    environment:
      - ETCDCTL_API=3
  etcd-config:
    build:
      context: .
      dockerfile: ./Dockerfile-etcd-config
    environment:
      - ETCDCTL_API=3
      - ETCDCTL_ENDPOINTS=etcd:2379
    depends_on:
      - etcd
    links:
      - etcd
  postgres:
    image: "postgres"
    volumes:
      - ./postgres-data:/data
    environment:
      POSTGRES_USER: "go_oauth2_server"
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: "go_oauth2_server"
  go-oauth2-server:
    depends_on:
      - etcd-config
      - postgres
    links:
      - etcd
      - postgres
    build:
      context: .
      dockerfile: ./Dockerfile
    image: go-oauth2-server:latest
    container_name: go-oauth2-server
    ports:
      - "8080:8080"
    environment:
      ETCD_ENDPOINTS: "http://etcd:2379"
    command: [go-oauth2-server, runserver]
